[application]
name = "Counter Example - Dioxus"
default_platform = "web"
out_dir = "dist"
#asset_dir = "public"

[web.app]
title = "Counter Example - Dioxus"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]

style = []
script = []

[web.resource.dev]

style = []
script = []

[[web.proxy]]
backend = "http://localhost:8000/"
